name: Analytics

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/analytics.yml'
      - 'analytics/**'
      - 'scripts/*'
      - 'scripts/analytics.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/analytics.yml'
      - 'analytics/**'
      - 'scripts/*'
      - 'scripts/analytics.sh'

  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

env:
  SAMPLE: Analytics
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}

jobs:
  cocoapods:
    name: spm - ${{ matrix.os }}
    runs-on: macOS-15
    strategy:
      matrix:
        os: [iOS, tvOS, macOS]
        xcode: ["16.1"]
        include:
          - os: iOS
            device: iPhone 16
            scheme: AnalyticsExample
            test: true
          - os: tvOS
            device: Apple TV 4K (3rd generation) (at 1080p)
            scheme: AnalyticsExampleTV
            test: true
          - os: macOS
            device: localhost
            scheme: AnalyticsExampleMac
            test: true
    env:
      OS: ${{ matrix.os }}
      SETUP: analytics
      SPM: true
      LEGACY: false
      DIR: analytics
      DEVICE: ${{ matrix.device }}
      TEST: ${{ matrix.test }}
      SCHEME: ${{ matrix.scheme }}
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          gem install xcpretty
          cd $SETUP
          ../scripts/install_prereqs/${SETUP}.sh
      - name: Build and Test SwiftUI (${{ matrix.os }})
        run: ./scripts/test.sh
